export enum UAType {
  None = 0,
  Aeroplane = 1,
  Helicopter = 2,
  Gyroplane = 3,
  HybridLift = 4,
  Ornithopter = 5,
  Glider = 6,
  Kite = 7,
  FreeBalloon = 8,
  CaptiveBalloon = 9,
  Airship = 10,
  FreeFall = 11,
  Rocket = 12,
  Tethered = 13,
  GroundObstacle = 14,
  Other = 15,
}
